---
- name: "Letsencrypt"
  include_tasks: tls.yaml
  when: >
    (mail.listen is defined and mail.listen|selectattr('tls', 'defined')|length > 0) or
    (web.sites is defined and web.sites|selectattr('tls', 'defined')|length > 0) or
    (web.relay.frontends is defined and web.relay.frontends|selectattr('tls', 'defined')|length > 0) or
    (apps.webdav.tls is defined)
