---
- name: "obsd : setup cron"
  include_tasks: cron.yaml
  when: >
    (base.cron is defined or base.autoupdate | default(false)) or
    (net is defined and net.routes is defined ) or
    (virt.vms is defined) or
    (mail.listen is defined and mail.listen|selectattr('tls', 'defined')|length > 0) or
    (web.sites is defined and web.sites|selectattr('tls', 'defined')|length > 0) or
    (web.relay.frontends is defined and web.relay.frontends |selectattr('tls', 'defined')|length > 0)
