---
- name: "isos : linux : openbsd : grab version" # noqa command-instead-of-module
  ansible.builtin.shell: set -o pipefail; curl http://ftp.openbsd.org/pub/OpenBSD/ | grep '"[0-9]\.[0-9]/"' | sed -e 's/\/<\/a>.*//'
    -e 's/.*>//' | sort | tail -n1
  register: obsd_latest
  changed_when: false

- name: "isos : linux : openbsd : download time notif"
  ansible.builtin.debug:
    msg: Downloading the latest OpenBSD ISO. This will take a while.

- name: "isos : linux : openbsd : grab latest iso"
  ansible.builtin.get_url:
    url: https://cdn.openbsd.org/pub/OpenBSD/{{ obsd_latest.stdout }}/amd64/install{{ obsd_latest.stdout | replace('.',
      '') }}.iso
    dest: /home/isos/openbsd-fsa-latest.iso
    mode: 0640

- name: "isos : linux : openbsd : patch image"
  ansible.builtin.shell: echo -e "set image /{{ obsd_latest.stdout }}/amd64/bsd.rd\nset tty com0" > boot.conf && growisofs -M /home/isos/openbsd-fsa-latest.iso -l -R -graft-points /etc/boot.conf=boot.conf
