---
- name: "isos : linux : debian : determine version" # noqa command-instead-of-module
  ansible.builtin.shell: set -o pipefail; curl https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/ | tr '=' '\n' |
    grep '"debian-[0-9][0-9]\.[0-9]\.[0-9]-amd64-netinst.iso"' | cut -d '>' -f1 | tr -d '"' | head -1
  register: deb_latest
  changed_when: false

- name: "isos : linux : debian : download time notif"
  ansible.builtin.debug:
    msg: Downloading the latest Debian ISO. This will take a while.

- name: "isos : linux : debian : download latest iso"
  ansible.builtin.get_url:
    url: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/{{ deb_latest.stdout }}
    dest: /home/isos/debian-fsa-latest.iso
    mode: 0640
