---
- name: dhcpd_syntax
  ansible.builtin.command: dhcpd -n
  changed_when: false

- name: iscdhcpd_syntax
  ansible.builtin.command: dhcpd -t -cf /etc/dhcp/dhcpd.conf
  changed_when: false

- name: dhcpd_restart
  ansible.builtin.service:
    name: dhcpd
    state: restarted
    enabled: true

- name: dhcpleased_restart
  ansible.builtin.service:
    name: dhcpleased
    state: restarted
    enabled: true
