---
- name: "alpine : install gitea"
  ansible.builtin.include_tasks: alpine_gitea.yaml
  when: ansible_distribution | lower == 'alpine'

- name: "openbsd : install gitea"
  ansible.builtin.include_tasks: openbsd_gitea.yaml
  when: ansible_distribution | lower == 'openbsd'
