---
- name: "gitea : openbsd : install the package"
  community.general.openbsd_pkg:
    name:
      - gitea
    state: present
  notify:
    - gitea_restart

- name: "gitea : openbsd : create configdir"
  ansible.builtin.file:
    path: /var/gitea/custom/conf
    state: directory
    owner: _gitea
    group: _gitea
    mode: "0755"
  notify:
    - gitea_restart

- name: "gitea : openbsd : template defaults"
  ansible.builtin.template:
    src: gitea.ini.j2
    dest: /etc/gitea/app.ini
    mode: "0600"
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

- name: "gitea : openbsd : add settings"
  community.general.ini_file:
    path: /etc/gitea/app.ini
    section: "{{ configitem.section }}"
    option: "{{ configitem.option }}"
    value: "{{ configitem.value }}"
    mode: "0600"
  loop: "{{ apps.gitea.config }}"
  loop_control:
    loop_var: configitem
  when: apps.gitea.config is defined
  notify:
    - gitea_restart
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
