---
- name: "virt : architecture check"
  ansible.builtin.fail:
    msg: VMD only on x64... sorry
  when: ansible_facts.machine != 'amd64' and ansible_facts.machine != 'x86_64'

- name: "openbsd : vmd"
  include_tasks: openbsd_vmd.yaml
  when: ansible_facts['os_family']|lower == 'openbsd'

- name: "alpine : kvm"
  include_tasks: alpine_kvm.yaml
  when: ansible_facts['os_family']|lower == 'alpine'
