---
- name: "set up dhcpd"
  ansible.builtin.include_tasks: dhcpd.yaml
  when: ( net.ifaces is defined and net.ifaces | selectattr('dhcp', 'defined') | length > 0 ) or
    ( virt.vms is defined and virt.vms|selectattr('install', 'defined')|length > 0 )
