---
- name: "obsd : wireguard : create keyfolder"
  ansible.builtin.file:
    path: /etc/wireguard
    state: directory
    mode: 0700

# todo: find a better way to gen the privkey before upping the iface
- name: "obsd : wireguard : install wgconf"
  community.general.openbsd_pkg:
    name: wireguard-tools
    state: present

- name: "obsd : wireguard : generate wgkeys"
  ansible.builtin.shell: if ! [ -f /etc/wireguard/{{ item.name }}.key ]; then wg {{ item.act }} > /etc/wireguard/{{ item.name
    }}.key; echo 'changed'; fi
  loop:
    - { name: secret, act: genkey }
    - { name: preshared, act: genpsk }
    - { name: public, act: pubkey < /etc/wireguard/secret.key }
  register: keygen_result
  changed_when: keygen_result.stdout == 'changed'

- name: "obsd : wireguard : set key permissions"
  ansible.builtin.file:
    path: /etc/wireguard/{{ item }}.key
    mode: 0600
  loop:
    - secret
    - preshared

# we got at least 1 peer with undefined pubkey
- name: "obsd : wireguard : retrieve keys"
  include_tasks: openbsd_wgkeys.yaml
  when: net.vpn.peers | rejectattr('pubkey', 'defined') | length > 0

- name: "obsd : wireguard : read my privkey"
  ansible.builtin.slurp:
    src: /etc/wireguard/secret.key
  register: myprivkey

- name: "obsd : wireguard : read my psk"
  ansible.builtin.slurp:
    src: /etc/wireguard/preshared.key
  register: mypsk

- name: "obsd : wireguard : set up iface"
  ansible.builtin.template:
    src: hostname.wgX.j2
    dest: /etc/hostname.wg0
    mode: 0600
  notify:
    - wg_netstart
