---
- name: "obsd : syslog"
  include_tasks: syslog.yaml
  when: net.dns is defined or net.dhcp is defined or web.relay is defined or web.sites is defined
  # this is effectively all roles that have a syslog dep
