---
- name: "obsd : setup syslog.conf"
  ansible.builtin.template:
    src: syslog.conf.j2
    dest: /etc/syslog.conf
    mode: 0644
  notify: syslogd_restart

- name: "obsd : setup newsyslog.conf"
  ansible.builtin.template:
    src: newsyslog.conf.j2
    dest: /etc/newsyslog.conf
    mode: 0644
