---
# apart from itself, httpd is required for:
# - letsencrypt
# - virtualization
# - webdav app
# and unfortunately, letsencrypt itself also has multiple triggers
- name: "webserver"
  include_tasks: httpd.yaml
  when: >
    web.httpd is defined or
    (web.relay.frontends is defined and web.relay.frontends|selectattr('tls', 'defined')|length > 0) or
    (mail.listen is defined and mail.listen|selectattr('tls', 'defined')|length > 0) or
    (virt.vms is defined and virt.vms|selectattr('install', 'defined')|length > 0)
