---
- name: "obsd : php : determine available versions" # noqa risky-shell-pipe
  ansible.builtin.shell: "ftp -o - https://cdn.openbsd.org/pub/OpenBSD/$(uname -r)/packages-stable/{{ ansible_facts.machine }}/ |\
    \ tr '=' '\n' | grep php-{{ web.php.version }} | cut -d '>' -f1 | grep -v debug | tail -1 | cut -d '-' -f2 | cut\
    \ -d '.' -f1-3"
  register: phpversion
  changed_when: false

- name: "obsd : php : install php"
  community.general.openbsd_pkg:
    name:
      - php-{{ phpversion.stdout }}

- name: "obsd : php : install libs"
  community.general.openbsd_pkg:
    name:
      - php-{{ phplib }}-{{ phpversion.stdout }}
  loop: "{{ web.php.libs }}"
  loop_control:
    loop_var: phplib
  when: web.php.libs is defined

- name: "obsd : php : conf base"
  ansible.builtin.copy:
    src: /usr/local/share/examples/php-{{ phpversion.stdout.split('.')[0:2] | join('.') }}/{{ setting.src }}
    dest: /etc/php-{{ phpversion.stdout.split('.')[0:2] | join('.') }}/{{ setting.dst }}
    mode: 0640
    remote_src: true
  loop:
    - { src: php.ini-production, dst: php.ini }
    - { src: opcache.ini, dst: opcache.ini }
  loop_control:
    loop_var: setting
  notify:
    - php_syntax
    - php_restart

- name: "obsd : php : conf libs"
  ansible.builtin.copy:
    src: /usr/local/share/examples/php-{{ phpversion.stdout.split('.')[0:2] | join('.') }}/{{ phplib }}.ini
    dest: /etc/php-{{ phpversion.stdout.split('.')[0:2] | join('.') }}/
    mode: 0640
    remote_src: true
  loop: "{{ web.php.libs }}"
  loop_control:
    loop_var: phplib
  when: web.php.libs is defined
  notify:
    - php_syntax
    - php_restart
