---
- name: php_syntax
  ansible.builtin.command: php-fpm-{{ phpversion.stdout.split('.')[0:2] | join('.') }} -t

- name: php_restart
  ansible.builtin.service:
    name: php{{ phpversion.stdout.split('.')[0:2] | join('') }}_fpm
    state: restarted
    enabled: true
